#spring:
#
#    jpa:
#      hibernate:
#        ddl-auto: create
#        #2022-05-08_yeoooo DDL이 설정되어있다면 자동으로 테이블을 drop하고 다시 만들어준다.
#      properties:
#        hibernate:
#          show_sql: true
#          #2022-05-08_yeoooo show_sql 옵션은 hibernate가 날리는 모든 쿼리를 보여준다.
#          format_sql: true
#          #2022-05-08_yeoooo format_sql 옵션은 inline이 아닌 format에 맞춰서 보여준다.
#    logging:
#      level:
#        org.hibernate.SQL: debug
#        org.hibernate.type: trace
#        #2022-05-08_yeoooo jpa, hibernate가 날리는 모든 쿼리를 보여준다.
#        #2022-05-08_yeoooo 하지만 show_sql(sys.out.print)과는 다르게 log로 보여준다. 권장.

spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/dev/java/projects/Linguine
#    username: sa
#    password:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/linguine?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

# 2022-06-30_yeoooo:  이미지 파일 전송 설정
  servlet:
    multipart:
      enabled: true


  jpa:
    database: mysql

    hibernate:
      ddl-auto: create-drop
        #2022-05-08_yeoooo: DDL이 설정되어있다면 자동으로 테이블을 drop하고 다시 만들어준다.
    properties:
      hibernate:
        show_sql: true
          #2022-05-08_yeoooo: show_sql 옵션은 hibernate가 날리는 모든 쿼리를 보여준다.
        format_sql: true
          #2022-05-08_yeoooo: format_sql 옵션은 inline이 아닌 format에 맞춰서 보여준다.
    defer-datasource-initialization: true

      #2022-12-15_yeoooo: 외부 스크립트 초기화용 옵션(2.5.0 이후)

  sql:
    init:
      platform: mysql
      encoding: UTF-8
      mode: always
#      mode: never

  profiles:
    include: oauth


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
        #2022-05-08_yeoooo: jpa, hibernate가 날리는 모든 쿼리를 보여준다.
        #2022-05-08_yeoooo: 하지만 show_sql(sys.out.print)과는 다르게 log로 보여준다. 권장.
